#!/usr/bin/env perl

# ABSTRACT: A command without an extension
# PODNAME: shellcmd

=head1 SYNOPSIS

    shellcmd -h
    shellcmd -v

=head1 DESCRIPTION

This is a command whose POD should be available from L<shellcmd>.
