# PODNAME: Statocles::Help
# ABSTRACT: Get help for Statocles

=head1 GUIDES

=head2 CONFIGURATION

To get started with your own Statocle site, run the C<statocles create>
command, or see L<the Statocles config help in
Statocles::Help::Config|Statocles::Help::Config>.

=head2 CONTENT

To use Statocles to manage content, see L<Statocles::Help::Content>.

=head2 THEMING

To change how your Statocles site looks, see L<Statocles::Help::Theme>.

=head2 DEPLOYING

To deploy your Statocles site to a Git repository, or any remote server, see
L<Statocles::Help::Deploy>.

=head2 DEVELOPING

To develop custom Statocles applications, custom ways to deploy, custom template
languages, or other extensions, see L<Statocles::Help::Develop>.

=head1 SUPPORT

=head2 IRC

To get real-time help, L<visit the #statocles channel on
irc.perl.org|https://chat.mibbit.com/?channel=%23statocles&server=irc.perl.org>.
Be patient, it's a slow channel.

=head1 SEE ALSO

For news and documentation, L<visit the Statocles website at
http:E<sol>E<sol>preaction.github.ioE<sol>Statocles|http://preaction.github.io/Statocles>.

