# PODNAME: Statocles::Help
# ABSTRACT: Get help for Statocles

=head1 GUIDES

=head2 CONFIGURATION

To get started with your own Statocles site, run the C<statocles create>
command, or see L<the Statocles config help in
Statocles::Help::Config|Statocles::Help::Config>.

=head2 CONTENT

To use Statocles to manage content, see L<Statocles::Help::Content>.

=head2 THEMING

To change how your Statocles site looks, see L<Statocles::Help::Theme>.

=head2 DEPLOYING

To deploy your Statocles site to a Git repository, or any remote server, see
L<Statocles::Help::Deploy>.

=head2 DEVELOPING

To develop custom Statocles applications, custom ways to deploy, custom template
languages, or other extensions, see L<Statocles::Help::Develop>.

=head2 UPGRADING

If you're upgrading from a previous version of Statocles, check
L<Statocles::Help::Upgrading> for any potential problems.

=head2 POLICIES

For information on development and deprecation, see L<Statocles::Help::Policy>.

=head1 MODULES

=over 4

=item *

L<Statocles>

=over 4

=item *

L<Statocles::App> - Base app role

=over 4

=item *

L<Statocles::App::Blog> - Blog application

=item *

L<Statocles::App::Perldoc> - POD application

=item *

L<Statocles::App::Plain> - Plain Markdown pages

=item *

L<Statocles::App::Static> - Static files

=back

=item *

L<Statocles::Base> - Base module bundles

=item *

L<Statocles::Command> - Command module

=item *

L<Statocles::Deploy> - Base deploy role

=over 4

=item *

L<Statocles::Deploy::File> - Deploy to a local directory

=item *

L<Statocles::Deploy::Git> - Deploy to a git repository

=back

=item *

L<Statocles::Document> - Default document class

=item *

L<Statocles::Event> - Event classes

=item *

L<Statocles::Help> - This document

=over 4

=item *

L<Statocles::Help::Config> - Configure the site.yml file

=item *

L<Statocles::Help::Content> - Writing content documents

=item *

L<Statocles::Help::Deploy> - Deploying the site

=item *

L<Statocles::Help::Develop> - Developing apps and plugins

=item *

L<Statocles::Help::Policy> - Project development and deprecation policies

=item *

L<Statocles::Help::Theme> - Develop themes and templates

=item *

L<Statocles::Help::Upgrading> - Upgrading themes, apps, and plugins

=back

=item *

L<Statocles::Link> - A link to another place

=item *

L<Statocles::Page> - Base page role

=over 4

=item *

L<Statocles::Page::Document> - Display a single document

=item *

L<Statocles::Page::File> - Display a static file

=item *

L<Statocles::Page::List> - Display a list of other pages

=item *

L<Statocles::Page::ListItem> - A single item in a list page

=item *

L<Statocles::Page::Plain> - Page with pre-generated HTML

=back

=item *

L<Statocles::Plugin::LinkCheck> - Check for broken links in the site

=item *

L<Statocles::Site> - Main site class

=item *

L<Statocles::Store::File> - Storage for documents and files

=item *

L<Statocles::Template> - Default template class

=item *

L<Statocles::Test> - Helpful test routines

=item *

L<Statocles::Theme> - Default theme class

=item *

L<Statocles::Types> - Types library

=item *

L<Statocles::Util> - Utility functions

=back

=back

=head1 SUPPORT

=head2 IRC

To get real-time help, L<visit the #statocles channel on
irc.perl.org|https://chat.mibbit.com/?channel=%23statocles&server=irc.perl.org>.
Be patient, it's a slow channel.

=head1 SEE ALSO

For news and documentation, L<visit the Statocles website at
http:E<sol>E<sol>preaction.github.ioE<sol>Statocles|http://preaction.github.io/Statocles>.

