# PODNAME: Statocles::Help::Content

=head1 DESCRIPTION

This guide describes how to use L<the statocles command|statocles> to manage
site content, build, test, and deploy the site.

=head2 Create A Blog Post

Remember when we gave our blog app a name? Now we can use that name to access
the blog's command-line commands. To create a new blog post, we can use the
C<post> command:

    $ statocles blog post My First Post
    New post at: blog/2014/06/04/my-first-post.markdown

Everything after C<post> will be used as the title of the post.

If you have the C<EDITOR> environment variable set, your editor will
automatically open on the newly-created document.

=head2 Build The Site

    $ statocles build

Running the C<build> command will write all our pages to the
C<.statocles-build> directory. We can open up this directory and look at the
files to make sure that our deploy will be correct.

=head2 Test The Site

    $ statocles daemon
    Listening on http://*:3000

Run the C<daemon> command to start an HTTP server to view your built site. This
will automatically build the site, so if you forgot to run C<build>, don't
worry.

If you edit any content, running C<build> again will update the site. On Mac
OS X, editing any content will automatically rebuild the site.

=head2 Commit Your Changes

    $ git add blog/2014/06/04/my-first-post.markdown
    $ git commit -m'My first post'

Once the build looks good, we'll want to commit our changes. The major feature
of having a website in a git repository is change tracking.

=head2 Deploy The Site

    $ statocles deploy

Running the C<deploy> command will, in the case of the Git deploy, commit the
updated pages to the Git repository. C<deploy> will try to do a C<git push>
automatically, so your changes are now live on Github Pages!

