# PODNAME: Statocles::Help::Setup
# ABSTRACT: How to set up a Statocles site

=head1 DESCRIPTION

This document describes how to get started using Statocles.

=head1 CREATE COMMAND

To use the site create command, make a directory for your new site
C<www.example.com>, change into that directory (C<cd www.example.com>), and run
C<statocles create>.

=head1 CONFIGURATION

To configure a Statocles site, see L<the Statocles config guide,
Statocle::Help::Config|Statocles::Help::Config>.

=head1 CONTENT

To begin working with the content on a Statocles site, see L<the Statocles
content guide, Statocle::Help::Content|Statocles::Help::Content>.

=head1 SEE ALSO

=over 4

=item L<Statocles::Help - The main Statocles help guide|Statocles::Help>

=back

